### ISSUE TITLE
Insert appears not to work with CKEditor 5

### ISSUE THREAD

**Issue by nattywebdev** [backdrop-contrib/insert#22]
When trying to insert a link to a document attached to a node (a pdf for example) into the Body field (CKEditor 5), it doesn't work. 

Instead this message is displayed in the developer console of Google Chrome:
```
insert.js?sggjji:198
Uncaught TypeError: $pane.size is not a function
    at Object.activateTabPane (insert.js?sggjji:198:15)
    at Object.insertIntoActiveEditor (insert.js?sggjji:177:23)
    at HTMLInputElement.insert (insert.js?sggjji:106:21)
    at HTMLInputElement.dispatch (jquery.js?v=3.7.1:2:40035)
    at v.handle (jquery.js?v=3.7.1:2:38006)
```
I tested this with a fresh build in tugboat, but had experienced it on several recently-updated sites (to Backdrop 1.28.2).

**Comment by nattywebdev** [comment]
This also applies to TinyMCE - the error displayed in console is the same.
According to @indigoxela : 

> size() has been deprecated in jQuery 1.8 (!!!) and removed in jQuery 3.
> That script is definitely broken with the most recent jQuery: https://github.com/backdrop-contrib/insert/blob/1.x-1.x/insert.js#L198

**Comment by nattywebdev** [comment]
I can confirm that the issue is not present if you switch back to jQuery 1 (Legacy), so at least there's a workaround, for now.

**Comment by indigoxela** [comment]
@jromine here's a [PR](https://github.com/backdrop-contrib/insert/pull/23) that addresses the jQuery compatibility problem.

More info in the documentation: https://api.jquery.com/size/

This does *not* address the CKEditor5 compatibility problem, which seem a lot trickier, but at least with that small change the module works with jQuery 3 and TinyMCE. :wink:

**Comment by quicksketch** [comment]
Thanks @indigoxela, I merged your bugfix PR as it seemed only beneficial. I'll take a look at making this work with CKE5. Wish me luck. :sweat_smile:

**Comment by quicksketch** [comment]
I was successful getting this working, but it's not super-clean. I filed a PR at https://github.com/backdrop-contrib/insert/pull/24.

The problem I encountered is that we need to track which CKEditor instance is the "active" one. TinyMCE politely provides `tinyMCE.activeEditor`. WYSIWYG module in D7 did something similar. But CKEditor 5 does not. In order to track which editor is active, we need to register each editor as it is created. That might take a few seconds after page load time, and we don't have the ability to register an event handler until after they're ready. To solve this problem cleanly and with 100% accuracy, we need a change to core, so I filed https://github.com/backdrop/backdrop-issues/issues/6770.

In the mean time, my PR works fine, but it might not work if you're on a particularly slow connection or computer, as it's just guessing when the loading is complete (2 seconds) rather than receiving a `ready()` event.

**Comment by nattywebdev** [comment]
This still needs work. With that PR, I am still getting this code inserted into the Body area, with a `<p>` tag round both the image and the link:

```
<p><img class="file-icon" src="/core/modules/file/icons/application-pdf.png" alt="" title="application/pdf" /></p>
<p>
    <a href="/files/docs/my-test-file.pdf" title="My test file"><span class="file">My test file</span></a> 
</p>
```

Clearly the `<p>` tags are unhelpful. 

As an enhancement, it would surely be cleaner to be able to add the image using a class in css, such as:

```
<a href="/files/docs/my-test-file.pdf" class="pdf-doc" title="application/pdf">My test file</a> 

```

where the class is added depending on the document type. The image can then be styled as needed.

**Comment by quicksketch** [comment]
Hi @nattywebdev, I'm working on fixing this issue. The Backdrop 1.30.0 release added a new API that https://github.com/backdrop-contrib/insert/pull/24 can now use (although #24 works in 1.30.0 as-is, it just could be better).

In your example, that problem happens when inserting a file link, is that correct? Inserting an image includes just a `<img>` tag and no wrapping markup at all. One of my clients has suggested that inserted images actually _should_ include a wrapping `<p>` tag. But for inserted file links, I think you're right that it should just be an `<a>` tag, with no extra image for the icon.

**Comment by quicksketch** [comment]
I updated the PR to use the new core API in 1.30.0+, which simplifies the PR a bit.

@nattywebdev I confirmed the problem you described when using the "Link to File (with icon)". The updated PR fixes this issue I think with the extra `<p>` tags getting added. Could you test again?

I did not change the actual markup for "Link to File (with icon)". I agree with you that adding a class would be a better solution, but the current solution matches existing core markup and the D7 version. There's probably a larger and separate issue that file icons should be reworked in some larger way, either using CSS and the current icons, or switching to Backdrop's Icon API.

**Comment by nattywebdev** [comment]
@quicksketch thanks for your attention to this issue. Yes, it was just when inserting a document link for me. Most things I can adjust via css, but the `<p>` tag wrapped around the `<img>` followed by another `<p>` is just too tricky!

One step forward is fine - I was just being cheeky asking for a further enhancement and of course understand why this is a step too far!

My customers love the Insert functionality - almost exclusively for file links - and it will be great to have it back. I will test shortly and report back.

**Comment by quicksketch** [comment]
One more tip: add `<span>` tags as an allowed tag in your text format, since the inserted content may need it to display properly. I have not checked if it's strictly required.

**Comment by nattywebdev** [comment]
I can confirm that patch #24 worked perfectly for me. Thank you @quicksketch - another great fix for my Backdrop customers!

**Comment by alanmels** [comment]
Unfortunately #24 didn't work for me with both jQuery 13 and jQuery 1

**Comment by quicksketch** [comment]
Thanks @alanmels, the PR at https://github.com/backdrop-contrib/insert/pull/24 needs to be updated to use the new active editor tracking provided by Backdrop core.
